title: DevilSec
description: ""
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  url: https://github.com/devilsec

twitter:
  url: https://twitter.com/devilsec1

orgsync:
  url: https://orgsync.com/181537/chapter

discord:
  url: https://discord.gg/MjNpC2C

wrccdc:
  url: wrccdc.html

htb:
  url: htb.html

team:
  url: team.html
