title: DevilSec
description: ""
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  repository_url: https://github.com/josephaorahim/asu_devilsec_website

twitter:
  url: https://twitter.com/devilsec1

orgsync:
  url: https://orgsync.com/181537/chapter

discord:
  url: https://discord.gg/MjNpC2C